name: Generate Snake (dark only)

on:
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:
  push:
    branches: ["main", "master"]

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate dark snake SVG
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: diogobitten
          outputs: |
            dist/github-contribution-grid-snake-dark.svg palette=github-dark

      - name: Show generated files
        run: |
          echo "Listing dist/"
          ls -la dist || true
          echo "---- file preview ----"
          head -n 20 dist/github-contribution-grid-snake-dark.svg || true

      - name: Publish to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
