name: Generate Snake (dark only)

on:
  schedule:
    - cron: "0 0 * * 1" # roda toda segunda-feira 00:00 UTC
  workflow_dispatch:      # permite rodar manualmente
  push:
    branches: ["main", "master"]  # roda quando você fizer push

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate dark snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: diogobitten
          outputs: |
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Publish to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
